server:
  port: 9003

spring:
  application:
    name: user

  jpa:
    hibernate:
      # This is the line you need to add or change
      ddl-auto: update
    # It's also helpful to see the SQL commands Hibernate is running
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver