services:
  mysqldb:
    container_name: mysqlcontainer
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-net
    # This healthcheck tells Docker to wait until MySQL is ready for connections
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  usermicroapplication:
    container_name: user-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    # This updated depends_on waits for the healthcheck to pass
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - springboot-mysql-net
    environment:
    - spring.datasource.url=jdbc:mysql://mysqlcontainer:3306/userdb?useSSL=false
    - spring.datasource.username=user
    - spring.datasource.password=user
    - spring.jpa.hibernate.ddl-auto=update
    - spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
networks:
  springboot-mysql-net:
    driver: bridge








#services:
#  mysqldb:
#    container_name: mysqlcontainer
#    image: mysql
#    environment:
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user
#      MYSQL_DATABASE: mysqldb
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - 3308:3306
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    networks:
#      springboot-mysql-net:
#
#services:
#  mysqldb:
#    container_name: mysqlcontainer
#    image: mysql
#    environment:
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user
#      MYSQL_DATABASE: userdb
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3309:3306"
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    networks:
#       springboot-mysql-net:
#    # This healthcheck tells Docker to wait until MySQL is ready for connections
##    healthcheck:
##      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
##      interval: 10s
##      timeout: 5s
##      retries: 5
#
#  usermicroapplication:
#    container_name: user-service
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "9003:9003"
#    # This updated depends_on waits for the healthcheck to pass
#    depends_on:
#      - mysqldb
#    environment:
#      - spring.jpa.hibernate.ddl-auto=update
#      - spring.datasource.url=jdbc:mysql://mysqlcontainer:3308/userdb
#      - spring.datasource.username=user
#      - spring.datasource.password=user
#      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#    networks:
#      springboot-mysql-net:
#    restart: on-failure

#  networks:
#    springboot-mysql-net:

#      mysqldb:
#        condition: service_healthy
#    networks:
#      - springboot-mysql-net
#
#networks:
#  springboot-mysql-net:
#    driver: bridge

